### ISSUE TITLE
Allow ISO 8601 date format in DB

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#105]

**Comment by AdamVig** [comment]
There is no clean built-in way in Knex.js or in the underlying MySQLJS library to transform incoming and outgoing datetimes between formats. I could change the columns to `varchar` and store an ISO 8601 string, but then I would lose the ability to use any of the built in MySQL datetime functionality.

@emmanuelroussel Would it be simple to change the datepicker's format to `YYYY-MM-DD` in the front end?
