### ISSUE TITLE
Block creation of item properties with same name

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#117]
You can currently create new brands, models and categories with a name that already exists. 

Do you think it makes sense for that comparison to ignore case?

**Comment by AdamVig** [comment]
- [x] Add a unique constraint in the brands, models, and categories tables to enforce uniqueness of combinations of organization ID and name
- [x] Investigate the difficulty of implementing a case-sensitive comparison on incoming database rows

**Comment by AdamVig** [comment]
MySQL ignores case by default on `VARCHAR` fields!
