### ISSUE TITLE
Disable imperative Issue subjects in GitMagic

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#12]
For the user story model it does not make sense for issue subjects to be imperative. Instead, they should just contain a simple summary of what the user story is in relation to.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/12/75de7ac9-4433-46e3-83ff-643536c63c9c/418a56b9-21d0-4330-b8b7-77c8391c19b6) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by emroussel** [comment]
Fixed with #31
