### ISSUE TITLE
Add organization endpoints

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#145]
When user auth is added in #13, the `/auth` endpoints will no longer create organizations. The `/organization` endpoints will be needed to accomplish this task.

**Comment by AdamVig** [comment]
Endpoints that require an organization ID could automatically extract it from the token sent in the authorization header. This may not be RESTful though, because the request would hit `/organization` and retrieve a single organization (in contrast with other endpoints, where the root path returns all of the entities it represents).

@emmanuelroussel what do you think? Would it be a hassle for you to find the current organization ID in the administration pages and send it with requests?

**Comment by emroussel** [comment]
It seems a bit tedious and could potentially create security concerns. If the client can choose what organization they are a part of. Could you simply get it from the db instead since you'll have the user id? Or would that create code duplication?

**Comment by AdamVig** [comment]
I am planning for the token to contain `userID`, `organizationID`, and `roleID`, so it would not even require getting the organization ID from the database. The functionality is trivial to implement either way (using the token or using the URL), the question is which is the Right Way.

With Restify, I can have either
`GET /organization` (get organization ID from token)
or
`GET /organization/:organizationID`
but not both.

So, I need to know which you prefer. In #155 I implemented the second option: `GET /organization/:organizationID` because it is consistent with our other endpoints, so that's the approach I prefer.

**Comment by emroussel** [comment]
Oh ok my bad. So with this, how will I be able to get the `organizationID` to the an organization's info?

**Comment by AdamVig** [comment]
You would get it on the creation of the organization, in the response from `PUT /organization`, but then you would have to store it client-side along with the token.

The alternative is to decode the token client-side and get the organization ID that way, but that seems like too much work and I am still unsure about decoding the token client-side.

So, I guess there is no practical way to use `GET /organization/:organizationID`, so I'll implement `GET /organization` (get organization ID from token).

(unless you have another idea 😄)

**Comment by emroussel** [comment]
Oh yeah decoding the token on the client actually makes sense. There's a library for that with `angular2-jwt` that I used to store the user ID, so I can just do the same for the organization ID.

**Comment by AdamVig** [comment]
Oh ok, great! I'll leave #155 as it is.
