### ISSUE TITLE
Add details to rentals

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#148]
Our client wants the ability to store extra information in rentals. Rentals already store the `userID` of the member of the organization who made the rental, but the client wants to be able to rent to external organizations. They want to store the following information:

- name of external company
- contact at external company
- rental notes

- [x] Add rental notes field (`varchar(1000)`)
- [x] Add table for external renters containing name, email, and phone
- [x] Add reference from rental to external renters table
- [x] Add endpoints for external renters

**Comment by AdamVig** [comment]
@emroussel How many characters do you think I should limit each of these fields to?

**Comment by emroussel** [comment]
Maybe 255 for name and contact and max for notes? Or is there much implications to have the max number of characters higher than needed?

**Comment by AdamVig** [comment]
At our scale, it doesn't matter much if the fields are larger than necessary.

I'll implement 255 characters!
