### ISSUE TITLE
Add kits of items

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#165]
A kit will store a list of model IDs that should be associated with each other.

- [x] Add table for kits (kit ID and name) and table for kit models (kit ID and model ID)
- [x] Add endpoints to get, get all, create, update, and delete kits
- [ ] Add endpoints to get all, create, and delete kit models
- [x] Add endpoint for model kits `GET /model/:modelID/kit`

`PUT /kit`
```JSON
{
  "name": "",
  "modelIDs": [23, 45, 54]
}
```

**Comment by AdamVig** [comment]
This endpoint will have to be different than most others. Instead of directly representing a database table, a kit is a synthesis of two tables. The `kit` table stores the name of the kit, and the `kitModels` table stores the models that belong in the kit.

Since models are related to brands, it will be possible to build a list of brands and models that belong in the kit so that a user can find items matching those brands/models and rent them together.

As specified above, the create kit endpoint will accept an array of models and a name for the kit. Kit names must be unique, because they will be identified to the user by their name. Using the names as the key for the kits can be dangerous, though, because they would need to be URL-encoded if they contain any non-ASCII characters. Thus, kits should have auto-incremented IDs and the name column should have a unique constraint.

- `PUT /kit`
```JSON
{
  "name": "",
  "models": [23, 45, 54]
}
```
Will create a row in the kit table and rows in the kit models table for each ID given in the `models` property. This will require a custom endpoint handler, because the endpoint service doesn't support this type of operation.
- `PUT /kit/:kitID`
- `GET /kit/:kitID`
I will need to figure out a useful format for kit responses to be in. Could be the same schema as creating kits, but then the UI would need to make requests for all of the models and brands in the response. Likely, it should have an array containing each entry in the kit, with each entry containing a model and a brand. However, this becomes less desirable when the nesting of entities becomes deeper and deeper as the API inevitably grows. It might make sense to start implementing a spec like [JSON API](http://jsonapi.org/), which supports including entities.
- `GET /kit`
- `DELETE /kit/:kitID`
This will be simple. All it has to delete is the row in `kit`, which will then `ON DELETE CASCADE` all of the related rows in `kitModels`. This can use a method from the endpoint service.

**Comment by AdamVig** [comment]
Proposed response format:
```JSON

{
  "name": "",
  "models": [
    {
      "modelID": 0,
      "name": "",
      "brand": {
        "brandID": 0,
        "name": ""
      }
    }
  ]
}
```

@emmanuelroussel would this work for you?

**Comment by emroussel** [comment]
Yep that looks good!

**Comment by AdamVig** [comment]
After attempting to implement the above response format for quite a while now, I have not made any progress towards a clean solution that is not working *against* the nature of SQL.

Here is an updated list of the kit endpoint data formats:
- `PUT /kit`
```JSON
{
  "name": ""
}
```
Instead of creating kits as a one-step process (including bulk addition of kit models), it makes more sense to separate the creation of the kit entity from the addition and deletion of the kit models. This will be reflected by a two-step process in the user interface: perhaps the user chooses the name for the kit, then is taken to a view where they can proceed to add and delete models one at a time.
- `PUT /kit/:kitID`
```JSON
{
  "name": ""
}
```
Same as the "create kit" endpoint.
- `GET /kit/:kitID`
```JSON
{
  "name": "",
  "kitID": 0,
  "organizationID": 0
}
```
- `GET /kit`
```JSON
{
  "results": [
    {
      "name": "",
      "kitID": 0,
      "organizationID": 0
    }
  ]
}
```
- `DELETE /kit/:kitID`

**Here's where it gets interesting:**
- `GET /kit/:kitID/model`
```JSON
{
  "results": [
    {
      "modelID": 0,
      "model": "",
      "brandID": 0,
      "brand": ""
    }
  ]
}
```
A conveniently assembled list of the models and brands that are a part of the requested kit.
- `PUT /kit/:kitID/model`
```JSON
{
  "modelID": 0
}
```
Add one model at a time. I could add a bulk insertion thing (it wouldn't be that hard), but that would make error handling a lot tougher on both the backend and frontend. For example, we could find ourselves asking which of the nineteen models from that request caused a foreign key error? I think it makes the most sense to use individual requests for each model addition (and deletion, see below :arrow_down:).
- `DELETE /kit/:kitID/model/:modelID`

@emroussel any pushback on this?

**Comment by emroussel** [comment]
It's hard to say without implementing it on the front end, but I think it does make sense. It also makes sense to build the UI around this structure.
