### ISSUE TITLE
Fix 401 Unauthorized on get user endpoint

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#181]
`GET /user/:userID`

Token is for the user that the request is trying to access (`userID` matches).

`401 Unauthorized`
> must be an administrator to access other users' data

**Comment by AdamVig** [comment]
Was not able to reproduce. @emmanuelroussel can you write out the steps to reproduce the bug?

**Comment by emroussel** [comment]
This is strange, the steps you described above are right.

1. `POST /auth` with credentials
2. `GET /user/:userID` with token received above (userID of the account)

I tried with two different accounts, same problem.

**Comment by AdamVig** [comment]
Restarted the server and the problem went away. 🙄
