### ISSUE TITLE
Add general metadata about items

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#19]
Add general information about items (brand, model, category).

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/19/75de7ac9-4433-46e3-83ff-643536c63c9c/4bac06f1-8341-4642-acee-247f85dd57cb) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
