### ISSUE TITLE
Check an item out for repair

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#21]
Mark an item as "in repair," disallowing it from being checked out.

**Comment by AdamVig** [comment]
I think that the real functionality behind this is not marking an item as "in repair," but is preventing users from checking out an item, which could be used for repair or for other purposes.

We could do this by adding a boolean field to the item entity that marks whether the item is allowed to be rented or not. Only admins would be able to toggle the value of that field.

That's only one approach, though, and maybe not the best one. @emroussel How would you like this to be implemented?

**Comment by emroussel** [comment]
On the front end, the user should probably go to a menu to mark items as "in repair" and scan the said item. I think a boolean field that I can modify with a simple PUT would make sense.

**Comment by AdamVig** [comment]
Closed as irrelevant.
