### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#24]
Instead of returning the entire inventory at once, return a certain number of items at a time.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/24/75de7ac9-4433-46e3-83ff-643536c63c9c/699148b7-73d3-43e6-a4bc-c3ff18da4b44) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/24/75de7ac9-4433-46e3-83ff-643536c63c9c/699148b7-73d3-43e6-a4bc-c3ff18da4b44) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by AdamVig** [comment]
Pagination will be implemented via query parameters, i.e. `?limit=50&offset=10`.

Source: [10 Best Practices for Better RESTful API](https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/)

**Comment by AdamVig** [comment]
Need to figure out how to send links to the first, last, next, and previous pages with paginated requests.

According to the source above, these links should be sent in the `Link` header. It would be nice to use a library to generate the links for this header, because they need to be URL encoded and in a specific format. On the client side, a library will be necessary as well.

To modify headers, the pagination function will need access to the response object (`res`), which will need to come from the endpoint service where it calls the passed modify function.

**Comment by AdamVig** [comment]
Decided to use [restify-links](https://www.npmjs.com/package/restify-links), a middleware for Restify that adds a `links()` function to all response objects, allowing link headers to easily be appended anywhere a `res` object can be found.

Added `res` to all modify functions so that they can change response headers.

Have to find a way to get the total number of items in the inventory in the `paginateQuery` function so that it can calculate the _next_ and _last_ links.

I considered implementing just the _previous_ and _next_ links, but even with those, it is necessary to know how many items there are in total so that the function will know when to stop generating _next_ links (otherwise it would go on infinitely, but the requests would stop yielding any results).

**Comment by AdamVig** [comment]
I have been attempting to add all of the pagination logic into a service that can be passed to the Knex `modify` method. This service would modify the database query by adding limit and offset as specified in the request parameters, while also adding the `Link` header to the response.

I have found that this approach will not work, and actually would be a bad idea because it breaks the separation of concerns principle. The service needs to count the rows in the database table that it is paginating in order to add the `Link` header, which requires a database query to count the rows, which returns a promise. The problem is that even though the service returns the promise, since it is passed to `Knex.modify()`, execution does not wait for the promise to complete.

Besides this problem, it violates separation of concerns because the service would be modifying the query and the response headers all in the same place.

The better alternative to this approach is to use two functions: one, `paginate.paginateQuery`, would be used in `Knex.modify()` to add the request parameters `offset` and `limit` to the database query. The other, `paginate.addLinks`, would be used as the last middleware on the endpoint, and would add the `Link` header to the response before it sends.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
