### ISSUE TITLE
Allow multiple identical items in kits

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#258]
Currently, users cannot create a kit with more than one item with the same brand and model (it returns a `409 Conflict` with the message `Already exists`).

However, this would be useful for smaller items such as batteries, since you often would want to rent more than one with a kit. 

It also might be more intuitive to add a quantity property on kit items instead of allowing multiple identical kit items. It would also be easier to implement on the front end and provide a better UX.

The error message mentioned above could also be more precise.

- [x] Add quantity column to `kitModel` table with default value `1`
- [x] Add optional quantity field to "create kit model" endpoint
- [x] Add "update kit model" endpoint for changing quantity of a kit model

**Comment by AdamVig** [comment]
Adding a task list to the first comment for progress tracking.
