### ISSUE TITLE
Add ability to view whole inventory

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#26]
View all items in inventory.

See #24 for pagination of inventory and #25 for inventory filtering.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/26/75de7ac9-4433-46e3-83ff-643536c63c9c/cc507ef5-8d57-4b11-b791-2ffb17c87376) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/26/75de7ac9-4433-46e3-83ff-643536c63c9c/cc507ef5-8d57-4b11-b791-2ffb17c87376) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by AdamVig** [comment]
Closed by #62.
