### ISSUE TITLE
Fix GitMagic rules

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#31]
They seem to have been overwritten by GitMagic bot at some point.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/31/75de7ac9-4433-46e3-83ff-643536c63c9c/f65990c1-5623-44d8-b694-d46f7f38f26f) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/31/75de7ac9-4433-46e3-83ff-643536c63c9c/f65990c1-5623-44d8-b694-d46f7f38f26f) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
