### ISSUE TITLE
Send sortIndex with create and update response

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#374]
When a user creates or updates any entity on the app (item, kit, custom field, etc.), they get out of order, because the entity in the store is replaced by the one sent back from the api.

Ideally, the api would send the corresponding `sortIndex` so that entities keep their order.

**Comment by AdamVig** [comment]
Returning a `sortIndex` for only the updated or created item would not work, because it’s likely that the `sortIndex`es of the whole list change any time there is an update. Closing in favor of [app/#437](https://github.com/stockpile-co/app/issues/437).
