### ISSUE TITLE
Improve organization of test fixtures

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#57]
The use of test fixtures has helped to prevent duplication of code in unit tests, but the fixtures themselves are organized in an illogical way.

**Currently**, there are fixtures named after the tests that use them (`./fixtures/auth.json`, `./fixtures/db.json`).

**Instead**, fixtures should be named after database entities they represent. This way, fixtures can be shared between tests.

**Currently**, since there is at most one fixture per test file, the fixtures are imported as `d` (for "data"). For example, `const d = require('./fixtures/db.json`)`.

**Instead**, fixtures should be loaded by a central module (`./fixtures/index.js`) that can be imported to each test as `f`, like `const f = require('./fixtures`)`. Inside the test, entities can be used as `f.[name of entity]`, like `f.organization`.

**Comment by AdamVig** [comment]
@emmanuelroussel can you think of a better short name for imported fixtures than `f`? I want to keep it to four or fewer letters, because it will be repeated all over the place in the tests.

**Comment by emroussel** [comment]
`f` is not very descriptive, but it works if you wanna keep it short. There's always `fixt` or `fxtr` maybe?

**Comment by AdamVig** [comment]
- [x] Change test fixture variable name in all tests from `d` to `fixt`

I changed my mind about reorganizing test fixtures. The current approach, of having unique data for each test, actually works pretty well. The asynchronous nature of Ava lends itself to conflicts with using the same database tables and data, so using totally separate data works well with the framework. Plus, when removing a test, it is a simple matter to remove all the data it relies upon: just delete the fixture file with the same name. If data was shared, it would be tricky to delete only the correct data, and the fixtures files may become bloated.
