### ISSUE TITLE
Add error handling for token missing information

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#66]
It has been seen in testing that some tokens can cause a MySQL error to be returned from the API because they do not have `organizationID` encoded in them.

Error handling should be added in the authentication controller where the JWT is decoded. A `400 Bad Request` error should be returned with the message `cannot find organization ID in token, please get new token`.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/66/75de7ac9-4433-46e3-83ff-643536c63c9c/c01c5325-c655-4c6f-9cf9-31ef6e73e290) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/66/75de7ac9-4433-46e3-83ff-643536c63c9c/c01c5325-c655-4c6f-9cf9-31ef6e73e290) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
