### ISSUE TITLE
Fix HATEOAS

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#70]
HAL is kinda of a pain.

- [ ] `/api` does not return any link except the root

**Comment by AdamVig** [comment]
This could be caused by #67, where I removed all of the leading slashes from route paths. `restify-json-hal` could be using a RegEx internally that counts on leading slashes on route paths.

**Comment by AdamVig** [comment]
Now that restify-json-hal is broken, it is worth looking into specifications that are more formally defined and have more traction than HAL. [JSON API](http://jsonapi.org/) looks promising.
