### ISSUE TITLE
Add full data to item response

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#78]
Add joins with the brand, model, status and category tables on the IDs contained in `item`. This should happen on both `/item` and `/item/:itemID`.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/78/75de7ac9-4433-46e3-83ff-643536c63c9c/fbbea886-1805-429e-84cf-4ae67894e8d3) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/78/75de7ac9-4433-46e3-83ff-643536c63c9c/fbbea886-1805-429e-84cf-4ae67894e8d3) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by AdamVig** [comment]
This depends on #100, which will add the ability to use the endpoint service while adding endpoint-specific joins to queries.
