### ISSUE TITLE
Test ticket from Code Climate

### ISSUE THREAD

**Issue by AdamVig** [AdamVig/stockpile-api#9]

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/9/75de7ac9-4433-46e3-83ff-643536c63c9c/a47b54fe-1924-48bf-9bd0-5ad39b13d376) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/9/75de7ac9-4433-46e3-83ff-643536c63c9c/a47b54fe-1924-48bf-9bd0-5ad39b13d376) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
