### ISSUE TITLE
Change status of item when rental is created

### ISSUE THREAD

**Issue by emroussel** [AdamVig/stockpile-api#95]
This could cause a problem if the organization is allowed to modify statuses, but there is currently no way to tell if an item is rented or not.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/95/75de7ac9-4433-46e3-83ff-643536c63c9c/30816eb0-3142-46f2-908b-06c1899ef00e) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must be shorter than 51 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-shorter-than)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/95/75de7ac9-4433-46e3-83ff-643536c63c9c/30816eb0-3142-46f2-908b-06c1899ef00e) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by AdamVig** [comment]
This will require auto-populating every organization with the statuses "Rented" and "Available" (see #91). Then, the script will have to discern which status should be set when the item is rented. This could be done with another database table that stores a relation between a `statusID` and an action, like `statusID: 1, organizationID: 37, action: 'rent'`. This would provide the most future flexibility.

For now, though, it may be simpler to use the same item statuses for all organizations.

**Comment by emroussel** [comment]
I agree that for now, we can simply use the same statuses for all organization

**Comment by AdamVig** [comment]
Upon further discussion, we decided that having a `status` column in the `item` table at all is a bad practice. `status` is related to the presence of the item in the `rental` table, meaning there is a dependency that the application must maintain (if rental exists, status must be "rented", if rental does not exist, status must be "available").

All `status` does is represent whether the item is rented, available, or in repair. Being in repair is a special form of being rented, so really the only two statuses are "rented" or "available". With this in mind, it is easy to replace the `status` column with a query that checks if a row with `itemID` in the `rental` table exists or not. If it does exist, then the item is rented, and if not, then it is available.

Further status information could be added with a field `typeID` in `rental` which would reference the table `type`, which could store different possible types of rentals. Then, when joining the `item` table with the `rental` table, a `status` field could be created that would be based on the state of the `rental` table.

**Comment by AdamVig** [comment]
- [x] Remove `statusID` column from item table
- [x] Remove `status` table
- [x] Remove `/status` APIs
- [ ] Add endpoint for item status

**Comment by AdamVig** [comment]
The changes discussed above close #90.
